gdsgdfgdf

diff --git a/.github/workflows/pr-scratch-org.yml b/.github/workflows/pr-scratch-org.yml
--- a/.github/workflows/pr-scratch-org.yml
+++ b/.github/workflows/pr-scratch-org.yml
@@ -1,7 +1,7 @@
 name: Create scratch org for PR
 on:
   pull_request:
-    types: [opened, reopened, synchronize]
+    types: [opened, reopened, synchronize, closed]
     # branches:
     #   - "scratch-alpha/**"
 
@@ -10,9 +10,69 @@ permissions:
   issues: write
 
 jobs:
+  delete:
+    name: Delete PR scratch org
+    if: ${{ github.event.action != 'syncronize' }}
+    runs-on: ubuntu-latest
+    steps:
+      ############## Setup ##############
+      - uses: actions/checkout@v4
+      - uses: actions/setup-node@v3
+        with:
+          node-version: 18
+
+      - name: Get PR number
+        uses: actions/github-script@v6
+        id: get_issue_number
+        with:
+          script: |
+            if (context.issue.number) {
+              // Return issue number if present
+              return context.issue.number;
+            } else {
+              // Otherwise return issue number from commit
+              return (
+                await github.rest.repos.listPullRequestsAssociatedWithCommit({
+                  commit_sha: context.sha,
+                  owner: context.repo.owner,
+                  repo: context.repo.repo,
+                })
+              ).data[0].number;
+            }
+          result-encoding: string
+      - name: Get scratch org alias
+        id: get_org_alias
+        run: echo "alias=pull-request-${{ steps.get_issue_number.outputs.result }}" >> "$GITHUB_OUTPUT"
+
+      - name: Install sfdx
+        run: npm install @salesforce/cli@2.9.8 --global
+
+      - name: Authenticate
+        env:
+          SFDX_AUTH_FILE: ${{ secrets.SFDX_AUTH_FILE }}
+        run: |
+          echo "${SFDX_AUTH_FILE}" > auth.json
+          sf org login sfdx-url --sfdx-url-file auth.json --set-default-dev-hub --set-default --alias devhub
+          rm auth.json
+
+      - name: Query existing PR scratch org
+        id: query_current_org
+        run: echo 'status=$(sf org display --target-org=${{ steps.get_org_alias.outputs.alias }} --json | jq .status)' >> "$GITHUB_OUTPUT"
+
+      ############## Delete ##############
+
+      - name: Delete existing PR scratch org
+        run: |
+          if [ "${{ steps.query_current_org.outputs.status }}" != "0" ]; then
+            echo "Failed to get info about current scratch org. Aborting."
+            exit 1
+          fi
+          sf org delete scratch --target-org=${{ steps.get_org_alias.outputs.alias }} --no-prompt
+
   create:
     name: Create PR scratch org
-    if: github.event.action == 'opened' || github.event.action == 'reopened'
+    if: ${{ github.event.action == 'opened' || github.event.action == 'reopened' }}
+    needs: delete
     runs-on: ubuntu-latest
     steps:
       ############## Setup ##############
@@ -60,11 +120,6 @@ jobs:
         run: echo 'status=$(sf org display --target-org=${{ steps.get_org_alias.outputs.alias }} --json | jq .status)' >> "$GITHUB_OUTPUT"
 
       ############## Create ##############
-
-      - name: Delete existing PR scratch org
-        # Do nothing if the scratch org doesn't exist
-        if: steps.query_current_org.outputs.status == 0
-        run: sf org delete scratch --target-org=${{ steps.get_org_alias.outputs.alias }} --no-prompt
 
       - name: Create scratch org
         run: |
