ffasdfasdf

diff --git a/.github/workflows/scratch-create.yml b/.github/workflows/scratch-create.yml
--- a/.github/workflows/scratch-create.yml
+++ b/.github/workflows/scratch-create.yml
@@ -68,8 +68,14 @@ jobs:
       - name: Create scratch org
         id: create_org
         run: echo data='$(sf org create scratch --json --edition=developer --alias=${{ steps.get_org_alias.outputs.alias }} --set-default --duration-days=14)' >> "$GITHUB_OUTPUT"
-      - name: Print scratch org data
-        run: echo "${{ steps.create_org.outputs.data }}"
+
+      - name: Abort creation
+        # Abort if something went wrong
+        if: ${{ fromJson(steps.create_org.outputs.data).status }} == 1
+        run: |
+          echo "Something went wrong during scratch org creation. Aborting."
+          echo "Error: ${{ fromJson(steps.create_org.outputs.data).message }}"
+          exit 1
 
       - name: Deploy source
         run: sf project deploy start --target-org=${{ steps.get_org_alias.outputs.alias }} --dry-run
