action (#2)
* action

* no action (#1)

* no action

* remove branch filters

* proper config

* oopd

* aaaa

* sddf

* fasfdsf

* gdfsggdgd

* dfsdafdsfsd

* ggfgsdg

* dsafsdfsdf

* gfdsgdfgf

* fdsafdsfasdf

* gsdgfdg

* ffasdfasdf

* fgdsgfdgdf

* gfsggdfg

* gdsgdfgdf

* fsadsfs

* gsfgdf

* ffgdsgsgfd

* fgsdfgdfg

* fgdfgfd

* gfdsdfg

* fsdfdsfds

* safdsfdsf

* bgdsdgdfsgdf

* gsfgfdg

* fsafsfsdfdsaf

* gfsggdfgsdf

* fsdgsfdgdf

* gsgdgdfg

* gsdgdfsg

* fgsdgfg

* gsgfdsgfg

* fggfdgfd

* dfafds

* gdsgdgfd

* letsfl

* dsgfdgdf

* fgdfgd

* gdsgdfgdf

* vdsdgdgdf

* please

* dfsfdfd

* comment

* gfdsgdfg

* bhjbjhb

* fdfsdfsd

* prtoprt gfdsgdfg

* print

* fgsdfg

diff --git a/.github/workflows/scratch-delete.yml b/.github/workflows/scratch-delete.yml
--- a/.github/workflows/scratch-delete.yml
+++ b/.github/workflows/scratch-delete.yml
@@ -1,14 +1,16 @@
-name: Delete PR Scratch Org
+name: Delete scratch org
 on:
   pull_request:
-    types: [closed]
+    types: [assigned]
     # branches:
     #   - "scratch-alpha/**"
 
 jobs:
   delete:
+    name: Delete PR scratch org
     runs-on: ubuntu-latest
     steps:
+      ############## Setup ##############
       - uses: actions/checkout@v4
       - uses: actions/setup-node@v3
         with:
@@ -41,18 +43,23 @@ jobs:
         run: npm install @salesforce/cli@2.9.8 --global
 
       - name: Authenticate
+        env:
+          SFDX_AUTH_FILE: ${{ secrets.SFDX_AUTH_FILE }}
         run: |
-          echo "${secrets.SFDX_AUTH_FILE}" > auth.json
+          echo "${SFDX_AUTH_FILE}" > auth.json
           sf org login sfdx-url --sfdx-url-file auth.json --set-default-dev-hub --set-default --alias devhub
           rm auth.json
 
       - name: Query existing PR scratch org
         id: query_current_org
-        env:
-          PR_NUMBER: ${{ steps.get_issue_number.outputs.result }}
-        run: sf org display --target-org=pull-request-${PR_NUMBER} --json >> "$GITHUB_OUTPUT"
+        run: echo 'status=$(sf org display --target-org=${{ steps.get_org_alias.outputs.alias }} --json | jq .status)' >> "$GITHUB_OUTPUT"
+
+      ############## Delete ##############
 
       - name: Delete existing PR scratch org
-        # Do nothing if the scratch org doesn't exist
-        if: fromJson(steps.query_current_org.outputs).status == 0
-        run: sf org delete scratch --target-org=${{ steps.get_org_alias.outputs.alias }} --no-prompt
+        run: |
+          if [ "${{ steps.query_current_org.outputs.status }}" != "0" ]; then
+            echo "Failed to get info about current scratch org. Aborting."
+            exit 1
+          fi
+          sf org delete scratch --target-org=${{ steps.get_org_alias.outputs.alias }} --no-prompt
diff --git a/.github/workflows/scratch-deploy.yml b/.github/workflows/scratch-deploy.yml
--- a/.github/workflows/scratch-deploy.yml
+++ b/.github/workflows/scratch-deploy.yml
@@ -1,13 +1,15 @@
 #.github/workflows/main.yml
-name: Deploy code to PR Scratch Org
+name: Deploy to scratch org
 on:
   pull_request:
-    types: [synchronize]
+    # types: [synchronize]
+    types: [assigned]
     # branches:
     #   - "scratch-alpha/**"
 
 jobs:
   deploy:
+    name: Deploy to PR scratch org
     runs-on: ubuntu-latest
     permissions:
       # Allow creating comments
@@ -46,28 +48,26 @@ jobs:
         run: npm install @salesforce/cli@2.9.8 --global
 
       - name: Authenticate
+        env:
+          SFDX_AUTH_FILE: ${{ secrets.SFDX_AUTH_FILE }}
         run: |
-          echo "${secrets.SFDX_AUTH_FILE}" > auth.json
+          echo "${SFDX_AUTH_FILE}" > auth.json
           sf org login sfdx-url --sfdx-url-file auth.json --set-default-dev-hub --set-default --alias devhub
           rm auth.json
 
       - name: Query existing PR scratch org
         id: query_current_org
-        env:
-          PR_NUMBER: ${{ steps.get_issue_number.outputs.result }}
-        run: sf org display --target-org=pull-request-${PR_NUMBER} --json >> "$GITHUB_OUTPUT"
+        run: echo 'status=$(sf org display --target-org=${{ steps.get_org_alias.outputs.alias }} --json | jq .status)' >> "$GITHUB_OUTPUT"
 
       ############## Deploy ##############
 
-      - name: Abort deployment
-        # Abort if the scratch org doesn't exist
-        if: fromJson(steps.query_current_org.outputs).status != 0
-        run: |
-          echo "No scratch org found for this PR. Aborting deployment."
-          exit 1
-
       - name: Deploy source
-        run: sf project deploy start --target-org=${{ steps.get_org_alias.outputs.alias }} --dry-run
+        run: |
+          if [ "${{ steps.query_current_org.outputs.status }}" != "0" ]; then
+            echo "Failed to get info about current scratch org. Aborting."
+            exit 1
+          fi
+          sf project deploy start --target-org=${{ steps.get_org_alias.outputs.alias }} --dry-run
 
       - name: Comment deployment
         uses: actions/github-script@v6
